# ===== Main testing: Linux ======
language: python
dist: bionic
python:
  - 3.7

# blocklist
branches:
  except:
  - optimization-development

# ===== Build for each OS ======
matrix:
  include:
    - name: "Windows"
      os: windows
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install -r requirements.txt
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - WORCDEBUG=true
      install:
        - python setup.py -q install
        - git clone --single-branch --branch develop https://github.com/MStarmans91/WORCTutorial
      # 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
      # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only.
      script:
        - python WORCTutorial/WORCTutorialSimple.py
        - fastr trace "C:\Users\travis\AppData\Local\Temp\WORC_Example_STWStrategyHN\__sink_data__.json" --sinks features_train_CT_0_predict --samples HN1331
        - fastr trace "C:\Users\travis\AppData\Local\Temp\WORC_Example_STWStrategyHN\__sink_data__.json" --sinks classification --samples all
        - fastr trace "C:\Users\travis\AppData\Local\Temp\WORC_Example_STWStrategyHN\__sink_data__.json" --sinks performance --samples all
        - fastr trace "C:\Users\travis\AppData\Local\Temp\GS\DEBUG_0\tmp\__sink_data__.json" --sinks output --samples id_0__0000__0000
    - name: "Linux"
      before_install:
       - sudo apt-get -qq update
       - sudo apt-get remove swig
       - sudo apt-get install swig3.0
       - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
       - sudo apt-get -qq -y install git
       - pip install -r requirements.txt
      env:
        - WORCDEBUG=true
      install:
        - python setup.py -q install
        - git clone --single-branch --branch develop https://github.com/MStarmans91/WORCTutorial
        # 'python' points to Python 2.7 on macOS but points to Python 3.8 on Linux and Windows
        # 'python3' is a 'command not found' error on Windows but 'py' works on Windows only.
      script:
        - python WORCTutorial/WORCTutorialSimple.py
        - fastr trace /tmp/WORC_Example_STWStrategyHN/__sink_data__.json --sinks features_train_CT_0_predict --samples HN1331
        - fastr trace /tmp/WORC_Example_STWStrategyHN/__sink_data__.json --sinks classification --samples all
        - fastr trace /tmp/WORC_Example_STWStrategyHN/__sink_data__.json --sinks performance --samples all
        - fastr trace /tmp/GS/DEBUG_0/tmp/__sink_data__.json --sinks output --samples id_0__0000__0000

notifications:
  slack:
    secure: ytP+qd6Rx1m1uXYMaN7dFHnFNu+bCIcyugSnAY7BtbumJwCuEt8hbWvQ/sDoAKqxj5VYcnBlTRDn1gjg2t2shs7pBGgjdeZQpQglXyAtN4bz3suSUbQ9/RIwt+RPmbiTXkWQtoZ4q0DotydozKMnq8Cvhdy+d5pMqToER6kMq/WCC+Y/99mmnqO2VrWpvAvP6bBOWDvrk/C4u3y5m3Rp5iE7uAYR3TDTprIW9UNEntDoEYT2T+bidkDRl7DMsi8R4q4s/A6EhZpB4Tnhwz7ama155z77ywdZLhdmk5HJvngXcunVwH4v/l8DbBZU0PqMEJzaRMn/tQCCqjx1/unpyFCv+QuhmP5K4wo17R77jHlcn7SBkdzYr/CKHrilWuShmvOMCckBShpQw3H9PivcI6/G5mVA23tH+gJSQUbzZmBR683x7oQHmnK3g977yD/ufEvV6qME9HFXt3+jIzVEwsUjtJsTV/NsbHlErJfhBp8HJTpq6IRhtKcX9QS1i/APXcYcCSCFJe8tOTLN6xmAKBgONG3XOAvJwfwXbF+rmfjX0x6KMUuD5WmHLjMLhQp0dS00LV7C9s18UkFBgKydqvF2AMPUsbgIGyZ/Vz3v5nz7JiNLDfp0HxQpqAABpdwDHR3/CfuhCDcqzIXAgRgXaFrqCxqoH6OrsgRH6UxUXnM=
